{% set version = "6.4" %}

package:
  name: muninn
  version: {{ version }}

source:
  url: https://github.com/stcorp/muninn/archive/{{ version }}.tar.gz
  sha256: 6b4b374e7fd62d110b8c03f6992057d4c6f4140f356aa68b706d6e86264e6ec8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - muninn-attach = muninn.tools.attach:main
    - muninn-destroy = muninn.tools.destroy:main
    - muninn-export = muninn.tools.export:main
    - muninn-hash = muninn.tools.hash:main
    - muninn-info = muninn.tools.info:main
    - muninn-ingest = muninn.tools.ingest:main
    - muninn-list-tags = muninn.tools.list_tags:main
    - muninn-prepare = muninn.tools.prepare:main
    - muninn-pull = muninn.tools.pull:main
    - muninn-remove = muninn.tools.remove:main
    - muninn-retrieve = muninn.tools.retrieve:main
    - muninn-search = muninn.tools.search:main
    - muninn-strip = muninn.tools.strip:main
    - muninn-summary = muninn.tools.summary:main
    - muninn-tag = muninn.tools.tag:main
    - muninn-untag = muninn.tools.untag:main
    - muninn-update = muninn.tools.update:main

requirements:
  host:
    - python >=2.6
    - pip

  run:
    - libspatialite
    - psycopg2
    - python >=2.6
    - requests
    - tqdm
    - tabulate

test:
  imports:
    - muninn

about:
  home: https://github.com/stcorp/muninn
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: LICENSE
  summary: Muninn is a library and a set of command-line tools to create and manage data product catalogues and archives. It can function as a pure product metadata catalogue or it can manage a product archive together with its metadata catalogue.

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
