{% set version = "6.0" %}

package:
  name: muninn
  version: {{ version }}

source:
  url: https://github.com/stcorp/muninn/archive/{{ version }}.tar.gz
  sha256: cf8a93c15755b29974cd25671dcec78162371324b42531c5da38e272305fb31a

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python >=2.6
    - setuptools

  run:
    - libspatialite
    - psycopg2
    - python >=2.6
    - requests
    - tqdm
    - tabulate

test:
  imports:
    - muninn

about:
  home: https://github.com/stcorp/muninn
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: LICENSE
  summary: Muninn is a library and a set of command-line tools to create and manage data product catalogues and archives. It can function as a pure product metadata catalogue or it can manage a product archive together with its metadata catalogue.

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
